"""create fitness profiles table

Revision ID: 5052fc0477a4
Revises: 49e18fd1d91f
Create Date: 2026-09-23 22:54:33.425484

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5052fc0477a4"
down_revision: Union[str, Sequence[str], None] = "49e18fd1d91f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fitness_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(length=50), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("fitness_level", sa.String(length=30), nullable=False),
        sa.Column("goal", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fitness_profiles_id"), "fitness_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_fitness_profiles_user_id"), "fitness_profiles", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fitness_profiles_user_id"), table_name="fitness_profiles")
    op.drop_index(op.f("ix_fitness_profiles_id"), table_name="fitness_profiles")
    op.drop_table("fitness_profiles")
    # ### end Alembic commands ###
