"""complete_training_nutrition_mvp

Revision ID: 82d6be1a904f
Revises: cc8be0ff1fcf
Create Date: 2026-10-05 14:55:27.015963

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82d6be1a904f"
down_revision: Union[str, Sequence[str], None] = "cc8be0ff1fcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("calories", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("serving_grams", sa.Float(), nullable=True),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "calories >= 0 AND protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0",
            name="ck_food_macros",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("foods", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_foods_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "nutrition_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "splits",
        sa.Column("cycle_days", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["splits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("splits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_splits_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "weight_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.CheckConstraint("weight_kg > 0", name="ck_positive_weight"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "recorded_on", name="uq_weight_day"),
    )
    with op.batch_alter_table("weight_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_weight_entries_user_id"), ["user_id"], unique=False)

    op.create_table(
        "workouts",
        sa.Column("discipline", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workouts_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "meal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("food_name", sa.String(length=100), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("meal", sa.String(length=20), nullable=False),
        sa.Column("grams", sa.Float(), nullable=False),
        sa.Column("calories", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meal_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_meal_entries_recorded_on"), ["recorded_on"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_meal_entries_user_id"), ["user_id"], unique=False)

    op.create_table(
        "split_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("split_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["split_id"], ["splits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("split_id", "day", name="uq_split_day"),
    )
    with op.batch_alter_table("split_days", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_split_days_split_id"), ["split_id"], unique=False)

    op.create_table(
        "training_plans",
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("goal", sa.String(length=50), nullable=False),
        sa.Column("split_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["training_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["split_id"],
            ["splits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_training_plans_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("progression", sa.String(length=100), nullable=True),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("intensity", sa.String(length=50), nullable=True),
        sa.Column("tempo", sa.String(length=30), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workout_id", "position", name="uq_workout_position"),
    )
    with op.batch_alter_table("workout_exercises", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workout_exercises_exercise_id"), ["exercise_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workout_exercises_workout_id"), ["workout_id"], unique=False
        )

    op.create_table(
        "workout_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("workout_name", sa.String(length=100), nullable=False),
        sa.Column("performed_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workout_logs_performed_on"), ["performed_on"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_workout_logs_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_workout_logs_workout_id"), ["workout_id"], unique=False
        )

    op.create_table(
        "plan_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["plan_id"], ["training_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "week", "day", name="uq_plan_day"),
    )
    with op.batch_alter_table("plan_days", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_days_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "set_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("exercise_name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("prescribed_sets", sa.Integer(), nullable=True),
        sa.Column("prescribed_reps", sa.Integer(), nullable=True),
        sa.Column("prescribed_weight_kg", sa.Float(), nullable=True),
        sa.Column("prescribed_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("prescribed_distance_meters", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["log_id"], ["workout_logs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("log_id", "position", "set_number", name="uq_log_set"),
    )
    with op.batch_alter_table("set_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_set_results_log_id"), ["log_id"], unique=False)

    # Preserve legacy rows and classify their existing discipline strings.
    op.create_table(
        "disciplines",
        sa.Column("code", sa.String(50), primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
    )
    op.execute(
        "INSERT INTO disciplines (code, name) SELECT DISTINCT discipline, discipline FROM exercises"
    )
    with op.batch_alter_table("fitness_profiles") as batch_op:
        batch_op.add_column(
            sa.Column("days_per_week", sa.Integer(), nullable=False, server_default="3")
        )
        batch_op.add_column(
            sa.Column("session_minutes", sa.Integer(), nullable=False, server_default="45")
        )
        batch_op.add_column(
            sa.Column(
                "available_equipment", sa.JSON(), nullable=False, server_default='["bodyweight"]'
            )
        )
        batch_op.add_column(
            sa.Column(
                "preferred_discipline", sa.String(50), nullable=False, server_default="strength"
            )
        )

    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("source", sa.String(length=20), nullable=False, server_default="SYSTEM")
        )
        batch_op.add_column(
            sa.Column("visibility", sa.String(length=20), nullable=False, server_default="platform")
        )
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_exercises_owner_id"), ["owner_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_exercises_discipline", "disciplines", ["discipline"], ["code"]
        )
        batch_op.create_foreign_key("fk_exercises_owner", "users", ["owner_id"], ["id"])
        batch_op.create_foreign_key("fk_exercises_parent", "exercises", ["parent_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_constraint("fk_exercises_discipline", type_="foreignkey")
        batch_op.drop_constraint("fk_exercises_parent", type_="foreignkey")
        batch_op.drop_constraint("fk_exercises_owner", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_exercises_owner_id"))
        batch_op.drop_column("parent_id")
        batch_op.drop_column("visibility")
        batch_op.drop_column("source")
        batch_op.drop_column("owner_id")

    with op.batch_alter_table("set_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_set_results_log_id"))

    op.drop_table("set_results")
    with op.batch_alter_table("plan_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_days_plan_id"))

    op.drop_table("plan_days")
    with op.batch_alter_table("workout_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_logs_workout_id"))
        batch_op.drop_index(batch_op.f("ix_workout_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_workout_logs_performed_on"))

    op.drop_table("workout_logs")
    with op.batch_alter_table("workout_exercises", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_exercises_workout_id"))
        batch_op.drop_index(batch_op.f("ix_workout_exercises_exercise_id"))

    op.drop_table("workout_exercises")
    with op.batch_alter_table("training_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_plans_owner_id"))

    op.drop_table("training_plans")
    with op.batch_alter_table("split_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_split_days_split_id"))

    op.drop_table("split_days")
    with op.batch_alter_table("meal_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meal_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_meal_entries_recorded_on"))

    op.drop_table("meal_entries")
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workouts_owner_id"))

    op.drop_table("workouts")
    with op.batch_alter_table("weight_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weight_entries_user_id"))

    op.drop_table("weight_entries")
    with op.batch_alter_table("splits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_splits_owner_id"))

    op.drop_table("splits")
    op.drop_table("nutrition_targets")
    with op.batch_alter_table("foods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_foods_owner_id"))

    op.drop_table("foods")
    # ### end Alembic commands ###

    op.drop_table("disciplines")
    with op.batch_alter_table("fitness_profiles") as batch_op:
        batch_op.drop_column("preferred_discipline")
        batch_op.drop_column("available_equipment")
        batch_op.drop_column("session_minutes")
        batch_op.drop_column("days_per_week")
