"""create exercise and muscle groups

Revision ID: cc8be0ff1fcf
Revises: 5052fc0477a4
Create Date: 2026-09-28 00:14:40.770447

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc8be0ff1fcf"
down_revision: Union[str, Sequence[str], None] = "5052fc0477a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("discipline", sa.String(length=50), nullable=False),
        sa.Column("modality", sa.String(length=50), nullable=True),
        sa.Column("exercise_type", sa.String(length=50), nullable=False),
        sa.Column("equipment", sa.String(length=100), nullable=True),
        sa.Column("difficulty", sa.String(length=30), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_id"), "exercises", ["id"], unique=False)
    op.create_table(
        "muscle_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_muscle_groups_id"), "muscle_groups", ["id"], unique=False)
    op.create_table(
        "exercise_muscles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("muscle_group_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["muscle_group_id"], ["muscle_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_muscles_exercise_id"), "exercise_muscles", ["exercise_id"], unique=False
    )
    op.create_index(op.f("ix_exercise_muscles_id"), "exercise_muscles", ["id"], unique=False)
    op.create_index(
        op.f("ix_exercise_muscles_muscle_group_id"),
        "exercise_muscles",
        ["muscle_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercise_muscles_muscle_group_id"), table_name="exercise_muscles")
    op.drop_index(op.f("ix_exercise_muscles_id"), table_name="exercise_muscles")
    op.drop_index(op.f("ix_exercise_muscles_exercise_id"), table_name="exercise_muscles")
    op.drop_table("exercise_muscles")
    op.drop_index(op.f("ix_muscle_groups_id"), table_name="muscle_groups")
    op.drop_table("muscle_groups")
    op.drop_index(op.f("ix_exercises_id"), table_name="exercises")
    op.drop_table("exercises")
    # ### end Alembic commands ###
