"""Deterministic starter templates; no AI or clinical personalization."""

from app.schemas.training import (
    PlanDayCreate,
    Prescription,
    SplitCreate,
    SplitDayCreate,
    TrainingPlanCreate,
    WorkoutCreate,
)

DAY_PATTERNS = {
    1: [1],
    2: [1, 4],
    3: [1, 3, 5],
    4: [1, 2, 4, 6],
    5: [1, 2, 3, 5, 6],
    6: [1, 2, 3, 4, 5, 6],
}


def build_workouts(request, exercises, fitness_level, session_minutes=45, goal="general_fitness"):
    beginner = fitness_level.lower() in ("beginner", "principiante")
    result = []
    for day in range(request.days_per_week):
        prescriptions = []
        for index, exercise in enumerate(exercises):
            values = {"exercise_id": exercise.id, "position": index + 1}
            if request.discipline == "strength":
                values.update(
                    sets=1 if session_minutes < 20 else (2 if beginner else 3),
                    reps=12
                    if goal.lower() in ("muscle_gain", "hypertrophy", "ganancia_muscular")
                    else 8,
                    rest_seconds=90,
                    progression="Review completed sets before increasing load",
                )
            elif request.discipline == "running":
                values.update(
                    duration_seconds=min(session_minutes * 60, 900 if beginner else 1800),
                    intensity="easy conversational pace",
                )
            else:
                values.update(
                    duration_seconds=30, sets=2, rest_seconds=30, intensity="comfortable range"
                )
            prescriptions.append(Prescription(**values))
        result.append(
            WorkoutCreate(
                name=f"{request.discipline.title()} – session {day + 1}",
                discipline=request.discipline,
                description="Starter template generated by rules; review before use.",
                exercises=prescriptions,
            )
        )
    return result


def build_split(request, workouts):
    return SplitCreate(
        name=f"{request.discipline.title()} {request.days_per_week} days",
        cycle_days=7,
        days=[
            SplitDayCreate(day=d, workout_id=w.id)
            for d, w in zip(DAY_PATTERNS[request.days_per_week], workouts)
        ],
    )


def build_plan(request, split, goal):
    return TrainingPlanCreate(
        name=f"{request.weeks}-week {request.discipline} starter",
        weeks=request.weeks,
        goal=goal,
        split_id=split.id,
        schedule=[
            PlanDayCreate(week=week, day=d.day, workout_id=d.workout_id, phase="base")
            for week in range(1, request.weeks + 1)
            for d in split.days
        ],
    )
